FROM mcr.microsoft.com/vscode/devcontainers/rust:latest

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

